export const ADD_VICTIM = 'ADD_VICTIM';
export const REMOVE_VICTIM = 'REMOVE_VICTIM';
export const EDIT_VICTIM = 'EDIT_VICTIM';

export const SET_VICTIMS = 'SET_VICTIMS';
export const START_ADD_VICTIMS = 'START_ADD_VICTIMS';
export const START_REMOVE_VICTIM = 'START_REMOVE_VICTIM';